---
# tasks for role opensim robust services

# The opensim assets to be stored by FSassets. Default setting is that 
# assets are stored on the same file system as the database ea.
#  /vardb/mysql contains the database
#  /vardb/fsassets the assets
#  /vardb/backups the database and fsassets backup files
#
# To further increase performance these could be split over seperate disks

- name: create fsassets folders
  file:
    path: "{{ db_assets }}/{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
    mode: "0750"
  loop: ['data', 'tmp']
  when: ansible_nodename in "{{ groups['asset_services'] }}"
  tags: ['configure']

- name: Copy Robust.ini file from template into opensim/bin directory.
  template:
    src: Robust.ini.j2
    dest: "/home/{{ admin_user}}/{{ conf_dir }}/Robust.ini"
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
    mode: 0644
  tags: ['configure']
